.TH XBAN 1 xban\-VERSION
.SH NAME
xban \- hides the X mouse cursor on keypress and reveals it again when the
mouse cursor moves
.SH SYNOPSIS
.B xban
.RB [ \-hvf ]
.SH DESCRIPTION
xban is a simple window manager agnostic tool that hides the X cursor when the
keyboard is used and reveals it again when the mouse moves.

If additional features are desired such as:
  - hiding the mouse cursor automatically after a period of inactivity
  - ignoring keypresses when a modifier is used or
  - moving the cursor to a specific location when the cursor is hidden

then refer to the more elaborate xbanish project which covers this:
https://github.com/jcs/xbanish

.SH OPTIONS
.TP
.B \-h
prints help output
.TP
.B \-v
prints version information and exits
.TP
.B \-f
fork the process run in the background
.TP
.B \--hidecmd
external command to run when hiding the mouse cursor
.TP
.B \--showcmd
external command to run when revealing the mouse cursor
